##
## @generated by fbcode//common/rust/tools/reindeer/buckify
## Do not edit by hand.
##
## See https://fburl.com/rust-third-party for instructions on how to update this.
##

METADATA = {
    "licenses": [
        "MIT",
        "Apache-2.0",
    ],
    "maintainers": [],
    "name": "git-object",
    "upstream_address": "",
    "upstream_hash": "",
    "upstream_type": "",
    "version": "0.22.1",
}
